import { createServer } from "../src/server.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import type { LoadedSkill } from "../src/types.js";
import type { IncomingMessage, ServerResponse } from "node:http";

// Import pre-bundled skills (generated by scripts/bundle-skills.ts at build time)
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const skillsData = require("../src/skills.json");

const skills = skillsData as unknown as LoadedSkill[];

export default async function handler(
  req: IncomingMessage & { body?: unknown },
  res: ServerResponse,
) {
  // CORS headers for cross-origin MCP clients
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET, POST, DELETE, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type, mcp-session-id, mcp-protocol-version");
  res.setHeader("Access-Control-Expose-Headers", "mcp-session-id");

  if (req.method === "OPTIONS") {
    res.writeHead(204);
    res.end();
    return;
  }

  if (req.method === "GET" || req.method === "DELETE") {
    res.writeHead(405, { Allow: "POST" });
    res.end(JSON.stringify({
      jsonrpc: "2.0",
      error: { code: -32000, message: "Method not allowed." },
      id: null,
    }));
    return;
  }

  const server = createServer(skills);
  const transport = new StreamableHTTPServerTransport({
    sessionIdGenerator: undefined, // stateless
    enableJsonResponse: true,
  });

  await server.connect(transport);

  // Pass pre-parsed body if Vercel has already parsed it
  await transport.handleRequest(req, res, req.body);

  // Clean up when the response finishes
  res.on("close", () => {
    transport.close();
    server.close();
  });
}
